[workspace]
members = [
    "exercises/rust/hello-world",
    "exercises/rust/reverse-string",
    "exercises/rust/gigasecond",
    "exercises/rust/clock",
    "exercises/rust/anagram",
    "exercises/rust/space-age",
]
