name: rust-track
on:
  push:
    branches: [ master ]
    paths:
    - 'exercise/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'exercise/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      
    - uses: actions/checkout@v2
    - name: Test
      run: cargo test --verbose
